added  comments to my project file
harshmgor/rpc_restapi pull request #4
Opened 2018-12-25 11:21 UTC by smitM76

2018-12-25 11:25 UTC, codingquark requested changes
Comments are not supposed to say what code is, but what code is for.

It should complement your code. Help others understand the reasoning behind the code.

2018-12-25 12:14 UTC, codingquark requested changes

2018-12-25 12:14 UTC, codingquark commented on RestXam2_O/App17/App17/App17/MainPage.xaml.cs
> +    this classes veries as per json fields
Change `veries` to `varies`

2018-12-25 12:14 UTC, codingquark commented on RestXam2_O/App17/App17/App17/MainPage.xaml.cs
> +    which helps us to bind and hendles the json responce we gonna get from rpc call
`hendles` to `handles`

2018-12-25 12:14 UTC, codingquark commented on RestXam2_O/App17/App17/App17/MainPage.xaml.cs
> +    which helps us to bind and hendles the json responce we gonna get from rpc call
`responce` to `response`

2018-12-25 12:24 UTC, smitM76 commented on RestXam2_O/App17/App17/App17/MainPage.xaml.cs
> +    which helps us to bind and hendles the json responce we gonna get from rpc call
okk

2018-12-27 12:53 UTC, codingquark approved these changes

2018-12-27 12:53 UTC, merged